Host is: RUTHERFORD
Using interpreter: D:/richa/anaconda3/envs/thesis_env_windows/python.exe
New directory: /tmp/ci-sy3v26Qftb
File running inside: /tmp/ci-sy3v26Qftb/runner.py
Running problem: MW11, dimension: 10

------------------------ Evaluating instance: MW11_d10 ------------------------
Traceback (most recent call last):
  File "C:/Users/richa/AppData/Local/Temp/ci-sy3v26Qftb/runner.py", line 80, in <module>
    main()
  File "C:/Users/richa/AppData/Local/Temp/ci-sy3v26Qftb/runner.py", line 76, in main
    evaluator.do(num_samples=num_samples)
  File "C:\Users\richa\AppData\Local\Temp\ci-sy3v26Qftb\ProblemEvaluator.py", line 302, in do
    print(1/0)
ZeroDivisionError: division by zero
